upbound/up-sdk-go

- .github/workflows/backport.yml
- .github/workflows/commands.yml
https://github.com/upbound/.github
This PR propagates the Backport and Comment Commands workflows from the above repo. The Backport workflow has been updated to support backporting PRs from forks. The Comment Commands workflow adds support for two `/comment` commands:
* `/backport` Can be used to trigger a backport retroactively on a PR that didn't have a backport label when it was merged.
* `/points` Can be used to quickly add a `points/N` label to an issue to represent how big a task it is.
I have:
[contribution process]: https://git.io/fj2m9
I've tested both of these workflows in my own private repo that I use to test actions out.
> Propagate handy GitHub Actions

- service/common/data.go
- service/organizations/client.go
- service/organizations/client_test.go
- service/organizations/types.go
- service/robots/client.go
- service/robots/client_test.go
- service/robots/types.go
- service/tokens/types.go
Adds support for managing robots and listing them in the context of an organization.
xref https://github.com/upbound/up/issues/215
I have:
Covered via unit tests and tested against API with CLI.
```
🤖 (up) go run ./cmd/up robot create dan-cli -a upbound
upbound/dan-cli  created
🤖 (up) go run ./cmd/up robot list -a upbound
NAME                        ID                                     DESCRIPTION                                                      CREATED
...
dan-cli                     f33f5369-39b8-4033-95e6-47b9a3eba470                                                                    31s    
...   
🤖 (up) go run ./cmd/up robot delete dan-cli -a upbound
upbound/dan-cli deleted
```
> Add support for managing robots

- service/organizations/client.go
- service/organizations/client_test.go
- service/organizations/types.go
Needed for https://github.com/upbound/up/issues/285, supports the following PR: https://github.com/upbound/up/pull/286
This uses the `api.upbound.io/v1/organizations/:organization_id/` REST API
It supports managing members as well as invites for new members
Signed-off-by: Julien Duchesne <julien.duchesne@grafana.com>
> Add client to manage org users

- client.go
- errors/errors.go
- errors/errors_test.go
Consumes new error struct of response body from shimmer providing additional details about error when available.
Fixes #35 [154](https://github.com/upbound/squad-marketplace/issues/154)
I have:
Tested with locally built `up` against new error returning services in `DEV`:
```
> up repo create test-
up: error: Repository name does not meet constraints: Repository name must be between 1 and 63 characters long, must begin with at least one lowercase alphanumeric character, may not end in a hyphen and may not contain consecutive hyphens.
> up repo create test
daren/test created
> up repo create test-test
up: error: Repository Limit Exceeded: You've reached your repository limit on this account.
```
> consume new error struct from shimmer

- .github/workflows/backport.yml
- .github/workflows/ci.yml
- .github/workflows/commands.yml
- .github/workflows/labels.yml
- .github/workflows/tag.yml
- README.md
- service/configurations/client.go
- service/configurations/client_test.go
- service/configurations/types.go
This PR supports two new GET service endpoints for Upbound root configurations.
`GET /v1/configurations/{accountName}`
`GET /v1/configurations/{accountName}/{cfgName}`
I have:
- adapted some of the examples in this repository for `Get` and `List` Configurations
> Introduce new configurations package

- service/configurations/client.go
- service/configurations/client_test.go
- service/controlplanes/types.go
In anticipation of all managed control planes on Upbound requiring a Configuration to be installed, this change also updates the control plane creation parameters to include a configuration ID.
This preempts some changes in the API to return specific statuses/error responses (for example, a 403 when attempting to delete an in-use Configuration, or a Bad Request if configuration ID is not specified).
I have:
- adapted the examples in `_example` to test against the public API.
> Add configuration delete and update control plane response to include configuration information.

- _examples/userinfo/main.go
- service/userinfo/client.go
- service/userinfo/client_test.go
- service/userinfo/types.go
Adds a client that is able to fetch information about the signed in
user.
I have:
```
🤖 (up-sdk-go) go run _examples/userinfo/main.go 
Enter username: 
hasheddan
Enter password: 
[REDACTED]
Getting user info...
hasheddan
```
> Add userinfo client

- service/controlplanes/client_test.go
- service/controlplanes/options.go
Add support for a query parameter that is specific to listing control planes (`?configurationId=STRING`)
This parameter filters the list response to only include control planes that have the specified configuration deployed.
xref https://github.com/upbound/up/pull/298
I have:
New unit test, and local testing adapting the `_example`.
> Add control plane specific query parameters

- service/gitsources/client.go
Update gitsources login to take port
The port is required by the CLI: it's a local port that receives a callback when the authorization and installation of the GitHub app is complete. Clients that don't need the port can pass 0.
I have:
Manually tested with pending CLI changes against both local-dev and dev.
> Update gitsources login to take port

- service/configurations/client.go
- service/configurations/client_test.go
- service/configurations/types.go
Add new configuration template API. It only supports one method: LIST
Unit test & tested with local copy of the `up` CLI.
> Add new configuration template API.

- service/organizations/client.go
Added a helper function GetOrgID(). This will be used in the CLI to update some commands that currently take an org ID instead of an org name. 
I'm adding it to the SDK instead of the CLI because it's reusable.
I have:
Tested in the CLI.
> Added helper: GetOrgID

- service/tokens/types.go
In the upbound-api, owner of the token could be either a user or a robot. However, since the type of the ID is UUID in this type, we are not able to create a user token. Making it `string` allows for both types of owners to be used.
I have:
Not tested manually but local tests pass.
> Token owner ID should be able to accept both uint and UUID

- client.go
Otherwise, we get `0` for all errors because server does not return an error with `status` field.
I have:
Manually.
> client: set status on errors so that IsNotFound works for them

- service/configurations/client.go
- service/configurations/client_test.go
- service/configurations/types.go
Update List() for configurations. Previously, it only got one page of configuration (the first ten). Now it gets all configurations. 
Fixes https://github.com/upbound/up/issues/403
Tested locally with the up CLI.
> Get all configurations instead of just the first ten.

- service/controlplanes/types.go
We are relaxing the requirement that a control plane must have a configuration.
Fixes #
I have:
> Controlplanes: make Configruation optional

- service/controlplanes/types.go
This fully makes configurations optional by omitting configurations from the JSON.
I have:
Tested using a fork of the UP CLI:
```
minerva:~/src/up $ up ctp list -a upbound
NAME               ID                                     STATUS   CONFIGURATION            CONFIGURATION STATUS
tt-test-020        10731768-f73f-4613-abf0-53fd78935ca3   ready    configuration-rds-prod   ready
bh-nono            74a3a68c-b98b-422b-af9f-889eb5c58f03   ready    n/a                      n/a
```
> Control planes: make configuration truly optional

- .github/workflows/ci.yml
- .golangci.yml
- apis/query/v1alpha1/json.go
- apis/spaces/v1alpha1/backup_types.go
JSON can have primitive types at the root. They panic'ed on deepcopy.
> query/v1alpha1: fix deepcopy panic for non-objects in JSON

- apis/spaces/v1beta1/controlplane_types.go
Fixes issue due to CEL rules using gated values when the gate is set to false:
```
{"level":"info","ts":"2024-04-03T11:12:20Z","logger":"mxe-apis","msg":"failed to apply crd controlplanes.spaces.upbound.io","error":"cannot create object: CustomResourceDefinition.apiextensions.k8s.io \"controlplanes.spaces.upbound.io\" is invalid: [spec.validation.openAPIV3Schema.properties[spec].x-kubernetes-validations[0].rule: Invalid value: apiextensions.ValidationRule{Rule:\"!has(oldSelf.restore) || has(self.restore)\", Message:\"restore source can not be unset\", MessageExpression:\"\"}: compilation failed: ERROR: <input>:1:5: undefined field 'restore'\n | !has(oldSelf.restore) || has(self.restore)\n | ....^\nERROR: <input>:1:29: undefined field 'restore'\n | !has(oldSelf.restore) || …
```
> fix: gate rules using gated fields

- apis/spaces/v1alpha1/sharedbackupconfig_types.go
Just what it says on the label, removes a bad reference.
I have:
N/A
> Remove reference to Velero from SharedBackupConfig

- apis/spaces/v1beta1/controlplane_types.go
Writing connectionDetails for a ControlPlane is being deprecated in Spaces 1.3 and will be removed in 1.4. This changeset adds a deprecation notice to the current API.
I have:
> Add deprecation notices to ControlPlane ConnectionDetail fields

- service/spaces/crossplane/supported_versions.yaml
Adds 1.4.0 block for working against pre-releases that are starting to roll out in cloud.
I have:
N/A metadata file.
> Add 1.4.0 block for working against pre-releases in cloud

- apis/spaces/v1beta1/controlplane_types.go
This change adds a new CEL rule to ctp objects which prevents creating ctp resources with no version when the upgrade policy is "Non".
Fixes #
I have:
I've consumed the change in spaces repo and applied following manifests.
Rejected:
- Upgrade policy is None and no version:
```yaml
apiVersion: spaces.upbound.io/v1beta1
kind: ControlPlane
metadata:
labels:
org: foo
name: none-ctp
spec:
crossplane:
autoUpgrade:
channel: None
writeConnectionSecretToRef:
name: kubeconfig-ctp
```
- Upgrade policy is None and version is "":
```yaml
apiVersion: spaces.upbound.io/v1beta1
kind: ControlPlane
metadata:
labels:
org: foo
name: ctp
spec:
crossplane:
autoUpgrade:
channel: None
version: ""
writeConnectionSecretToRef:
name: kubeconfig-ctp
```
Accepted:
- No crossplane subfield defined:
```yaml
apiVersion: …
```
> Add CEL rule for rejecting empty version with upgrade policy "None"

- apis/upbound/v1alpha1/space_types.go
Part of https://github.com/upbound/team-orchestration/issues/99
Add the `apiURL` field to space status, which will pass the connect path for the space - used to get the ingress. The `FQDN` can be deprecated and removed later, once `up` transitions to querying for the host ingress and CA data from the space directly.
I have:
> Add new `apiURL` field to space status

- apis/spaces/v1alpha1/sharedbackupschedule_types.go
This PR removes the Last Schedule print column from the SharedBackupSchedule, since the `.status.lastBackupTime` field doesn't exist in the API.
Part of https://github.com/upbound/spaces/issues/980
I have:
> Remove Last Schedule print column from SharedBackupSchedule

- service/robots/client.go
- service/robots/types.go
- service/teams/types.go
- add create / delete for robot team memberships
- typed team response instead of generic DataSet to ex. extract names
Fixes #54
I have:
via up-cli PR:
```
up robot membership create chris test123 -a upboundcare
upboundcare/chris/test123 team membership created
```
```
up robot membership get chris -a upboundcare    
TEAM MEMBERSHIP
test444
test123
```
```
up robot membership delete chris test123 -a upboundcare
Are you sure you want to delete this robot team membership? This cannot be undone [y/n]: y
Deleting robot team membership upboundcare/chris/test123.
upboundcare/chris/test123 deleted
```
```
up robot membership get chris -a upboundcare
TEAM MEMBERSHIP
test444
```
> feat(robot): add options for robot teammembership + typed team responses

- service/repositorypermission/client.go
- service/repositorypermission/types.go
- add create, delete and list endpoint for repositorypermission
Fixes #52
I have:
with corresponding up-cli implementation:
```
up repo permission list test123 -a upboundcare
TEAM      REPOSITORY   PERMISSION   CREATED                UPDATED
test123   repo         write        2024-06-23T18:56:58Z   n/a
```
```
up repo permission delete test123 repo -a upboundcare
Are you sure you want to delete this repository permission? This cannot be undone [y/n]: y
Deleting repository permission for team "test123" in repository "repo"
Repository permission for team "test123" in repository "repo" deleted
```
```
up repo permission create test123 repo write -a upboundcare
Permission write granted to team test123 for repository repo in account upboundcare
```
> feat(sdk): add repositorypermission

- apis/spaces/v1beta1/conditions.go
- apis/spaces/v1beta1/controlplane_types.go
As part of the Spaces control plane provisioning improvements, this PR makes the following changes:
- Removes  `Scheduled` condition type
- Adds `Healthy` condition type
- Adds `ControlPlaneProvisioned` condition type
- Adds `status.message` field to communicate a user friendly message about the provisioning (replacing the existing `internal.spaces.upbound.io/message` annotation
- Updates print columns accordingly
I have:
Together with the relevant Spaces PR:
```
❯ kubectl get ctp -w
NAME   CROSSPLANE    READY   HEALTHY   MESSAGE   AGE
ctp    1.15.3-up.1                               3s
ctp    1.15.3-up.1   False   False     Waiting for control plane API   6s
ctp    1.15.3-up.1   False   False     Waiting for Crossplane pods to be ready   60s
ctp    1.15.3-up.1   True    False     Waiting …
```
> ControlPlanes: remove scheduled and add healthy condition

- apis/spaces/v1beta1/controlplane_types.go
Remove no longer used hostcluster id from status.
I have:
With the consuming PR on the Spaces side.
> Remove hostcluster id from control plane status

- apis/observability/v1alpha1/telemetry_types.go
Adds Validated condition, related to https://github.com/upbound/spaces/pull/1689
I have:
With https://github.com/upbound/spaces/pull/1689
> Add Validated condition to STC

- apis/spaces/v1beta1/controlplane_types.go
This PR drops healthy column from the ControlPlane print columns. We will enhance Message with a state to communicate health.
I have:
```bash
NAME   CROSSPLANE    READY   MESSAGE   AGE
test   1.15.5-up.2            Creating   3s
test   1.15.5-up.2   False   Creating   11s
test   1.15.5-up.2   False   Creating: Waiting for control plane API   11s
test   1.15.5-up.2   False   Creating: Waiting for control plane API: Gateway deployment not...   50s
test   1.15.5-up.2   True    Creating: There are unready deployments: external-secrets-opera...   64s
test   1.15.5-up.2   True    Available                                                            74s
test   1.15.5-up.2   True    Degraded: There are unready deployments: kube-state-metrics          7m
test   1.15.5-up.2   True    Available …
```
> ControlPlane: Drop healthy column

- apis/spaces/v1beta1/controlplane_types.go
- apis/spaces/v1beta1/zz_generated.deepcopy.go
Cleans up leftover Crossplane specific fields from when CTP used to be a managed resources.
Fixes #
I have:
- ~[] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.~
Locally.
Installed Spaces with the change, created CTP, all looked good.
Installed Spaces without the change, created CTP, applied new CTP CRD, all looked good.
> chore: clean up CTP from unused fields

- apis/spaces/v1beta1/controlplane_types.go
Adds `spec.class` field to ControPlane to support classes as described in https://github.com/upbound/arch/pull/245.
I have:
As part of https://github.com/upbound/spaces/pull/1916
> feat: control plane class

- service/repositories/client.go
- service/repositories/client_test.go
- service/repositories/types.go
It's now possible to create private repositories. Add an argument to `CreateOrUpdate` indicating whether a repository should be public and pass it to the API.
I have:
~- [ ] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.~
Updated unit tests, local integration into `up` CLI for testing against the real API.
> repositories: Add support for setting visibility

- apis/spaces/v1beta1/controlplane_types.go
remove unused `GitAuthType` for controlplane API
followup for https://github.com/upbound/spaces/pull/1323 and https://github.com/upbound/up-sdk-go/pull/95/ 
Fixes #
I have:
`make reviewable`
> cleanup(unused): remove GitAuthType

- apis/spaces/v1alpha1/resource_selector.go
- apis/spaces/v1alpha1/resource_selector_test.go
The resource selector logic for labels was wrong: if the first label selector has not been matching, the later were never considered.
> resource-selector: fix case with multiple label selectors

- apis/spaces/v1alpha1/resource_selector.go
- apis/spaces/v1alpha1/resource_selector_test.go
Backport of https://github.com/upbound/up-sdk-go/pull/135.
> Backport to 1.10: resource-selector: fix case with multiple label selectors

- apis/spaces/v1alpha1/resource_selector.go
- apis/spaces/v1alpha1/resource_selector_test.go
Backport of #135 
Fixes #
I have:
> [backport release-1.9] resource-selector: fix case with multiple label selectors

- apis/spaces/v1alpha1/resource_selector.go
- apis/spaces/v1alpha1/resource_selector_test.go
Backport of #135 
Fixes #
I have:
> [backport release-1.8] resource-selector: fix case with multiple label selectors

- apis/spaces/v1alpha1/resource_selector.go
- apis/spaces/v1alpha1/resource_selector_test.go
There were some commits missing in previous release-1.9 branch, so, created release-1.9-fixed from the correct commit (which Spaces release-1.9 depends on) and backporting this fix again.
Backports #135 
I have:
CI
> [Backport release-1.9-fixed] resource-selector: fix case with multiple label selectors

- apis/spaces/v1beta1/controlplane_types.go
Currently, we cannot provision control planes when their names are longer than 63 chars. The primary blocker for this is, we are adding a label on the host namespace with the value being control plane name. 
This PR defines a CEL rule to ensure it is not possible to create control planes with names longer than 63 chars.
I have:
```
❯ kubectl apply -f examples/controlplane/controlplane.yaml
The ControlPlane "upbound-composition-dynamodb-uptest-uptest-e2e-my-first-ddb-table" is invalid: <nil>: Invalid value: "object": control plane name cannot exceed 63 characters
❯ kubectl apply -f examples/controlplane/controlplane.yaml
The ControlPlane "upbound-composition-dynamodb-uptest-uptest-e2e-my-first-ddb-tabl" is invalid: <nil>: Invalid value: "object": control plane name cannot exceed 63 …
```
> Limit control plane name to 63 chars at max

- client.go
- http/headers/headers.go
- http/request/request.go
Starting small and adding just requestID. This should be pretty easy to extend in the future if we want to propagate other things from the client.
I have:
> Add new ContextTransport and wire up client initiated requestIDs for correlating logs

- apis/spaces/v1beta1/controlplane_types.go
To allow migrating between classes we need to allow updating ControlPlanes' `spec.class`, hence I removed the validation rule.
To allow defaulting at runtime to the runtime default class we need to remove the defaulting to `default` special class.
I have:
> feat: remove class defaulting and validation from controlplanes crd

- service/users/client.go
- service/users/client_test.go
- add users client for listTokens endpoint to get personal access tokens 
Fixes #
I have:
with up-cli private build:
```
up token list
NAME             ID                                     CREATED
chris-token      22749001-f3bd-43d0-8862-5cdeb7c061f6   33m
pat-token        246f0667-ecfc-4499-874e-d328119bb6a0   34m
test555          3273c6d6-b849-4763-b150-6fba7de7f7d2   38m
```
> feat(client): add users client
