- client.go
- service/accounts/client.go
- service/accounts/types.go
- service/controlplanes/client.go
- service/controlplanes/client_test.go
- service/controlplanes/types.go
- service/oldplanes/client.go
- service/oldplanes/client_test.go
- service/oldplanes/types.go
- service/tokens/client.go
Introduces a new `controlplanes` package that targets an updated API surface. The existing package has been moved to `oldplanes` and is deprecated. It is likely to be removed before the next release of `up-sdk-go`.
I have:
Unit test coverage has been updated, and the new package has been tested against a local instance of the updated API.
> Introduce new controlplanes service package

- service/common/options.go
- service/common/options_test.go
- service/controlplanes/client.go
- service/controlplanes/client_test.go
- service/controlplanes/types.go
Updates the controlplanes list method to support pagination via options.
I have:
Covered via unit tests.
> Update controlplanes list to support pagination

- client.go
- service/repositories/client.go
- service/repositories/client_test.go
- service/repositories/types.go
Adds a repositories client and basic methods.
xref https://github.com/upbound/up/issues/216
I have:
Covered via unit tests. Also tested against public Upbound API.
> Add repositories client

- service/accounts/types.go
- service/organizations/client.go
- service/organizations/client_test.go
- service/organizations/types.go
Adds an organizations service with Create / Get / List / Delete methods.
xref https://github.com/upbound/up/issues/223
I have:
Covered via unit tests and methods exercised as part of https://github.com/upbound/up/issues/223 implementation.
```
🤖 (up) up org list
NAME                 ROLE  
upbound              owner 
crossplane           owner 
dan                  owner 
...
🤖 (up) up org delete dan
dan deleted
```
> Add organizations service

- service/repositories/client_test.go
- service/robots/client.go
- service/robots/client_test.go
Updates robots client with the ability to list tokens, and also fixes an
impromper HTTP method on the Get operation.
I have:
Verified behavior via CLI consumption:
```
🤖 (up) go run ./cmd/up/ robot list -a dan
No robots found in dan
🤖 (up) go run ./cmd/up/ robot create cool-bot -a dan
dan/cool-bot created
🤖 (up) go run ./cmd/up/ robot list -a dan
NAME       ID                                     DESCRIPTION   CREATED
cool-bot   baf29497-bf22-4b0d-81af-7ee692c474d8                 12s   
🤖 (up) go run ./cmd/up/ robot token list cool-bot -a dan
No tokens found for robot cool-bot in dan
🤖 (up) go run ./cmd/up/ robot token create cool-bot cool-token -a dan
dan/cool-bot/cool-token created
🤖 (up) go run ./cmd/up/ robot token list cool-bot …
```
> Add support for listing tokens to robots client

- .github/workflows/ci.yml
- go.mod
- go.sum
- service/controlplanes/client_test.go
- service/organizations/client_test.go
- service/repositories/client_test.go
Bumping `build` submodule and fixing linter errors along the way.
I have:
`make reviewable`
> Bump build submodule and fix linter errors

- service/configurations/types.go
Add Private parameter for creating configurations
I have:
Tested manually with the up CLI. (PR for the up CLI will follow this one.)
> Add Private parameter for creating configurations

- service/organizations/types.go
Added new fields for organization members
I have:
Manually, via the up CLI.
> Add new fields for organization members.

- apis/spaces/v1alpha1/sharedbackupschedule_types.go
- apis/spaces/v1alpha1/zz_generated.deepcopy.go
> fix: SelectedControlPlanes, not SelectedControlplanes

- generate/generate.sh
- go.mod
- go.sum
- service/spaces/crossplane/supported_versions.yaml
- service/spaces/crossplane/versions.go
- service/spaces/crossplane/versions_test.go
This PR adds a supported versions file at `service/spaces/crossplane/supported_versions.yaml` together with the relevant type and basic validation. 
I have:
Unit test.
> Add supported versions file for Spaces/Crossplane

- apis/spaces/v1beta1/controlplane_types.go
> spaces/v1beta1: move group labels here

- apis/spaces/v1alpha1/sharedbackupconfig_types.go
[Prefix](https://github.com/thanos-io/objstore/blob/e8336a5fd5f38f13281cb69ee7c3a4262450d4fb/client/factory.go#L47) needs to be outside of the free form config.
I have:
N.A.
> feat(sharedbackupconfig): allow passing prefix

- service/spaces/crossplane/supported_versions.yaml
Adds the latest UXP releases.
I have:
> Add latest Crossplane versions

- apis/common/reference.go
- apis/spaces/v1alpha1/backup_types.go
- apis/spaces/v1beta1/controlplane_types.go
The docs for all backups references to configurations and restore sources were wrong, this updates them to be less specific in the internal struct, so that we can be more specific where they are used.
Fixes #
I have:
N.A.
> docs: fix backup references docs

- service/organizations/client.go
- service/organizations/types.go
- service/teams/client.go
- service/teams/client_test.go
- service/teams/types.go
implement teams service client parts of #54
Fixes #
I have:
tested the implementation from up-sdk-go with an implementation in up-cli 
added in go.mod
cat go.mod
```
[...]
replace github.com/upbound/up-sdk-go => ../up-sdk-go
```
```
up team create test-implementation -a upboundcare
upboundcare/test-implementation created
```
```
up team get test-implementation -a upboundcare   
NAME                  ID                                     CREATED
test-implementation   f68ca5fd-4a83-40bb-a620-3db3da3c9109   17s
```
```
up team list -a upboundcare
NAME                                       ID                                     CREATED
test123                                    5e8e8dab-3598-4003-a5ba-34a12859d60f   23m
test-implementation …
```
> feat(teams): add teams service client

- apis/query/v1alpha2/query_types.go
Missed pluralizing this when I introduced v1alpha2. Fairly certain no one is using it yet, so should be safe to fix.
I have:
~- [ ] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.~
It builds!
> query: Fix the json name of filters in relations

- apis/spaces/v1beta1/controlplane_types.go
Fixes defaulting of spec.class itroduced in https://github.com/upbound/up-sdk-go/pull/120
Fixes #
I have:
Tested with spaces
> fix: proper defaulting of class

- apis/spaces/v1beta1/controlplane_types.go
Add a better description for control plane spec.class and updates the classes gate flag to the current proposed one in https://github.com/upbound/spaces/pull/1916/files#r1805980906
I have:
N/A
> fix: Controlplane spec.class improvements

- apis/upbound/v1alpha1/space_types.go
Add the new `space.upbound.io/inaccessible` label to the SDK so it can be consumed by `up` CLI 
I have:
> Add space inaccessible label

- apis/admin/v1alpha1/spacebackup_types.go
- apis/admin/v1alpha1/spacebackupschedule_types.go
Pretty self-explanatory.
I have:
> docs: fix space backups docs leftovers

- service/repositories/types.go
add missing `repositoryTypeFunction`
Fixes #
I have:
> feat(repo): add repositorytypefunction

- apis/spaces/v1alpha1/zz_generated.backup_types.go
- apis/spaces/v1alpha1/zz_generated.backupschedule_types.go
- apis/spaces/v1alpha1/zz_generated.sharedbackup_types.go
- apis/spaces/v1alpha1/zz_generated.sharedbackupconfig_types.go
- apis/spaces/v1alpha1/zz_generated.sharedbackupschedule_types.go
- hack/duplicate_api_type.sh
Missed the matching line wasn't available and therefore v1alpha1 wasn't marked as storage version.
Unfortunately adding it also to `*List` resources, but doesn't do anything, so fine for now.
I have:
Pointed to local branch and generated CRDs.
> append storageversion to the right point

- apis/spaces/v1beta1/controlplane_types.go
Follow up to #145, exposing storage usage.
I have:
N.A.
> feat: controlplane storage usage status

- apis/spaces/v1beta1/controlplane_types.go
Missed updating printcolumns in #150
I have:
> fix: update printcolumn for class.size

- apis/spaces/v1beta1/controlplane_types.go
Add a status field showing the current class after a transition.
I have:
N.A.
> feat: add status.class.current

- apis/spaces/v1beta1/controlplane_types.go
We are hiding classes work for now so removing the print columns.
Fixes #
I have:
- ~[] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.~
> revert: ControlPlane size print columns

- apis/pkg/v1alpha1/controllerrevision_types.go
After we've bumped crossplane to v2, we need to have the `ControllerRevision` type implement the Crossplane's `PackageRevisionWithRuntime` interface to get the reconcilers correctly behave.
I have:
> ControllerRevision now implements xppkgv1.PackageRevisionWithRuntime
